// src/lib/api/index.ts
export * from './client'
export * from './clientAuth'
export * from './staffAuth'
export * from './reference'
export * from './demandes'
export * from './transactions'
export * from './releves'
export * from './agentDemandes'
export * from './gerantDashboard'
export * from './staffReclamations'
export * from './messagesAudio'